/**
 * Tooltip data for body types, species, and options in the Star Trek Character Icon Creator
 * This file contains descriptions and lore for various Star Trek elements
 */

/**
 * Tooltip information organized by category
 * @type {Record<string, Record<string, string>>}
 */
export const tooltipData = {
    bodyTypes: {
        humanoid: 'Standard bipedal form with two arms, two legs, and a head. Most Star Trek species are humanoid.',
        cetaceous: 'Aquatic species, such as the dolphins in Lower Decks or the Humpback whale in Prodigy.',
        exocomp: 'Small sentient robots designed for starship repairs.',
        medusan: 'Non-corporeal energy beings whose appearance is so alien it can drive humanoids insane. They are housed in protective containers.',
        'cal-mirran': 'Non-canon crystalline life forms from the Shackleton Expanse. Their consciousness exists within geometric crystal structures.',
        qofuari: 'Non-canon ursine (bear-like) species from the Shackleton Expanse. They have a strong sense of honor and tradition.',
        sukhabelan: 'Non-canon species from the Sarell Expanse. They possess a unique physiology adapted to their homeworld.'
    },

    calMirranShapes: {
        Prismatic: 'A multi-faceted angular crystal form',
        Spherical: 'A rounded, orb-like crystal structure',
        Pinwheel: 'A rotating, star-shaped crystal configuration',
        Cubical: 'A cube-shaped crystalline form'
    },

    ears: {
        none: 'No visible external ears. Species like Edosians and Saurians lack prominent ear structures.',
        round: 'Standard human-like rounded ears',
        pointy: 'Distinctive pointed ears typical of Vulcans, Romulans, and related species',
        ferengi: 'Large, lobed ears characteristic of the profit-driven Ferengi species',
        cat: 'Feline-style pointed ears seen in Caitians and Kzinti',
        bear: 'Bear-like rounded ears',
        horns: 'Horn-like protrusions in place of standard ears'
    },

    headFeatures: {
        'andorian-antennae': 'Two antennae protruding from the head. Andorians are a blue-skinned species from the ice moon Andoria.',
        'bolian-line': 'Distinctive vertical ridge running down the center of the face. Bolians are known for their blue skin and friendly demeanor.',
        'ferengi-brow': 'Pronounced cranial lobes and brow ridges. Is to be paired with the Ferengi ears.',
        'trill-spots': 'Leopard-like spots running from hairline down the sides of the body. Some Trill are joined with a symbiont.',
        'bird-beak': 'Avian-style beak for bird-like species',
        'tilikaal-headpiece': 'Ceremonial headpiece of the ancient Tilikaal species of the Shackleton Expanse',
        'bird-tuft': 'Feathered crest or tuft typical of avian species',
        'gill-whiskers-or-feathers': 'Gills, whiskers, or feather-like structures for aquatic or avian species',
        'cat-nose': 'Feline-style nose for Caitians and similar species',
        'tellarite-nose': 'Upturned porcine nose. Tellarites are known for their love of debate and argument.',
        'snout-nose': 'Extended snout-like nose structure, can also be used for Tellarites',
        tusks: 'Protruding teeth or tusks',
        'zakdorn-cheeks': 'Prominent jowls and facial structure. Zakdorn are renowned for their strategic thinking.',
        'benzite-nose': 'Smooth, noseless facial structure. Benzites often require a breathing apparatus in standard atmospheres.',
        'nose-ridges': 'Subtle ridges across the bridge of the nose. Bajorans are deeply spiritual and display these characteristic ridges.',
        'klingon-ridges': 'Pronounced cranial ridges. Klingons are a warrior culture valuing honor above all. (Style A)',
        'klingon-ridges-2': 'Pronounced cranial ridges. Klingons are a warrior culture valuing honor above all. (Style B)',
        'bifurcated-forehead-a': 'Split forehead ridge pattern (Style A)',
        'bifurcated-forehead-b': 'Split forehead ridge pattern (Style B)',
        'cardassian-forehead': 'Distinctive spoon-shaped ridge on forehead. Cardassians are known for their military discipline and cunning.',
        'cardassian-neck': 'Thick neck ridges extending from the jaw. A defining feature of Cardassian physiology.',
        'vin-shari-neck': 'Neck ridges of the VinShari species',
        'denobulan-ridges': 'Facial ridges that run horizontally. Denobulans are optimistic and practice polygamy.',
        'north-romulan-v': 'V-shaped forehead ridge seen in some Romulan lineages',
        'kelpian-lines': 'Distinctive ganglia and facial features. Kelpiens evolved as a prey species with heightened threat awareness.',
        'bajoran-earring': 'Traditional Bajoran earring worn on the right ear, signifying their faith and family.',
        'cyborg-antenna-l': 'Cybernetic antenna implant on left side',
        'cyborg-antenna-r': 'Cybernetic antenna implant on right side',
        'occular-implant-l': 'Cybernetic eye implant on left side, like some Borg technology',
        'occular-implant-r': 'Cybernetic eye implant on right side, like some Borg technology',
        'vulcan-cybernetic-implant': 'Cybernetic implant similar to Ensign Rutherford\'s from Lower Decks',
        'benzite-breather': 'Breathing apparatus required by some Benzites in standard atmospheres',
        'orion-head-bolting': 'Decorative head bolts worn by some Orions',
        'rimmer-h': 'Hologram indicator "H" on forehead from sci-fi sitcom Red Dwarf',
        'forehead-coin': 'Decorative coin or medallion worn on the forehead, such as Jaffa from Stargate SG-1',
        bindi: 'Traditional decorative dot worn on the forehead',
        'lower-stud-l': 'Decorative stud piercing on lower left face',
        'lower-stud-r': 'Decorative stud piercing on lower right face',
        'upper-stud-l': 'Decorative stud piercing on upper left face',
        'upper-stud-r': 'Decorative stud piercing on upper right face',
        'hoop-earring-l': 'Hoop earring on left ear',
        'hoop-earring-r': 'Hoop earring on right ear',
        'upper-hoop-earring-l': 'Upper hoop earring on left ear',
        'upper-hoop-earring-r': 'Upper hoop earring on right ear',
        'eye-scar': 'Scar across the eye, often signifying combat experience',
        'chakotay-tattoo': 'Traditional indigenous tattoo like Commander Chakotay\'s from Voyager',
        bandolier: 'Shoulder strap for carrying equipment or ammunition, such as worn by Worf',
        'medical-coat': 'White medical coat worn by Starfleet medical personnel',
        'lab-coat': 'Laboratory coat for science personnel',
        'red-overcoat': 'Red overcoat or jacket, pairs well with Klingon uniform for a captain or general\'s look',
        'mobile-emitter': 'Portable holographic emitter allowing holograms to exist outside the holodeck'
    },

    hats: {
        'romulan-23rd-helmet': '23rd century Romulan military helmet with distinctive design',
        'breen-helmet-24th': '24th century Breen refrigeration suit helmet. Breen identity is concealed within these suits.',
        'breen-helmet-32nd': '32nd century updated Breen helmet design',
        'blue-orion-helmet': 'Helmet worn by blue Orion pirates',
        'chefs-hat': 'Traditional chef\'s toque hat',
        'beanie-hat': 'Casual knit beanie cap',
        hoodie: 'Hooded sweatshirt in uniform color',
        'hoodie-alt': 'Hooded sweatshirt in accent color',
        'baseball-cap': 'Standard baseball cap',
        'baseball-cap-ds9ers': 'Deep Space 9ers team baseball cap',
        'baseball-cap-nx01': 'NX-01 Enterprise baseball cap',
        'guinan-hat': 'Elaborate decorative hat like those worn by Guinan in TNG',
        'bajoran-vedic-hat': 'Religious headwear worn by Bajoran Vedeks (clergy)',
        'bajoran-kai-hat-a': 'Ceremonial hat of Kai Opaka, spiritual leader of Bajor',
        'bajoran-kai-hat-b': 'Ceremonial hat of Kai Winn, later Kai of Bajor',
        'gangster-hat': 'Trilby hat, popular in mid-20th century Earth',
        'western-hat': 'Cowboy-style western hat',
        'top-hat': 'Formal top hat',
        bucket: 'Casual bucket hat in accent color',
        'starfleet-bucket-hat': 'Starfleet-style bucket hat'
    },

    eyewear: {
        visor: 'Visual sensor visor like Geordi La Forge\'s VISOR, allowing a blind person to see via electronic sensors',
        'blue-orion-mask': 'Face mask worn by blue Orion pirates',
        'grey-aviator-goggles': 'Captain Proton holodeck program goggles',
        sunglasses: 'Standard sunglasses',
        'glasses-thick': 'Thick-framed prescription glasses',
        'glasses-circle': 'Round circular glasses',
        'glasses-oval': 'Oval-shaped glasses',
        'glasses-cateye': 'Cat-eye style glasses'
    },

    noseTypes: {
        thick: 'Thick, prominent nose structure',
        small: 'Small, subtle nose',
        long: 'Elongated nose structure',
        humpback: 'Humpback whale-style facial structure'
    },

    uniformEras: {
        ENT: 'Enterprise era (2150s) - Early Starfleet uniforms with colored shoulders',
        'Mid 22nd': 'Mid-22nd century Starfleet design',
        'DISCO 23rd': 'Discovery era (2250s) - Starfleet uniforms with metallic delta insignia',
        'Pre-SNW': 'Pre-Strange New Worlds era uniforms',
        SNW: 'Strange New Worlds era (2259) - Updated 23rd century design',
        'SNW Minidress': 'Strange New Worlds era minidress variant',
        TOS: 'The Original Series (2260s) - Classic colored tunics with black pants',
        'TOS Minidress': 'The Original Series minidress variant',
        'TOS Films Enlisted': 'The Original Series films (2270s-2290s) enlisted uniforms',
        'TOS Films': 'The Original Series films officer uniforms - red jacket design',
        'Lost Era': 'Early 24th century transitional uniform design',
        'TNG Early': 'The Next Generation early (2360s) - Spandex jumpsuit with colored shoulder lines on black',
        'TNG Early Skant': 'The Next Generation early skant (skirt) variant',
        'TNG Early Provisional': 'The Next Generation provisional officer uniform',
        'TNG Early Admiral': 'The Next Generation early admiral uniform',
        TNG: 'The Next Generation (2360s-2370s) - Two-piece uniform with black shoulders and colored collar trim',
        'TNG Cadet': 'The Next Generation era Starfleet Academy cadet uniform',
        'TNG Provisional': 'The Next Generation era provisional officer uniform',
        'TNG Admiral': 'The Next Generation era admiral uniform',
        'VOY DS9': 'Voyager/Deep Space Nine (2370s) - Two-piece with colored shoulders and undershirt',
        'VOY Hazard Team': 'Elite Force game\'s Hazard Team tactical uniform',
        "VOY Seven's Uniform": 'Seven of Nine\'s unique catsuit from Voyager',
        'Captain Proton': 'Tom Paris\'s Captain Proton holodeck program costume',
        'Dominion War': 'Dominion War era (2370s) variant with gray shoulders',
        'Dominion War Admiral': 'Dominion War era admiral uniform (gold trim)',
        'DS9 Cadet': 'Deep Space Nine era cadet uniform',
        'Lower Decks': 'Lower Decks era (2380s) - Similar to Voyager style but with white dividing line',
        'Crisis Point 2': 'Crisis Point 2 holodeck program uniforms, Dominion war uniform with Lower Decks\' white dividing line',
        'Prodigy A': 'Star Trek: Prodigy era (2380s) design worn by Chakotay\'s crew',
        'Prodigy B': 'Star Trek: Prodigy era design variant worn by Voyager-A crew',
        'Picard Pre-S1': 'Picard pre-season 1 (2380s-2390s) uniforms',
        'Picard S1': 'Picard season 1 (2399) - Dark civilian-style uniforms',
        'Picard S2 Cadet': 'Picard season 2 Starfleet Academy cadet uniform',
        'Picard S3': 'Picard season 3 (2401) - colored shoulders with looser collar',
        'Flash-Forwards 25th': 'TNG, DS9, and VOY\'s "future" timeline uniforms',
        'VOY Timeship 29th': 'Voyager 29th century timeship crew uniforms',
        'DISCO 32nd Early': 'Discovery 32nd century (3180s) early design',
        'DISCO 32nd Late': 'Discovery 32nd century (3180s-3190s) later design',
        'Academy Cadet': 'Starfleet Academy cadet (student) uniform',
        'Academy Staff': 'Starfleet Academy staff uniform',
        'DISCO 33rd': 'Discovery 33rd century\'s epilogue design',
        'Andorian 22nd': '22nd century Andorian Imperial Guard uniform',
        'Andorian 23rd': '23rd century Andorian military uniform',
        'Cardassian Early 24th': 'Early 24th century Cardassian military uniform',
        'Cardassian 24th': '24th century Cardassian Central Command uniform',
        'Ferengi Early 24th': 'Early 24th century Ferengi civilian dress',
        'Ferengi Mid 24th': 'Mid-24th century Ferengi attire',
        'Klingon Early 23rd': 'Early 23rd century Klingon Empire uniform',
        'Klingon 23rd': '23rd century Klingon Defense Force uniform',
        'Klingon 24th': '24th century Klingon warrior uniform',
        'Klingon Bekk 24th': '24th century Klingon bekk (low-ranking warrior) uniform',
        'Orion Blue': 'Blue Orion Syndicate uniform',
        'Romulan 23rd': '23rd century Romulan Star Empire uniform',
        'Romulan 23rd Officer': '23rd century Romulan officer uniform',
        'Romulan 23rd Officer Minidress': '23rd century Romulan officer minidress',
        'Romulan 24th': '24th century Romulan uniform (early)',
        'Romulan 24th Officer': '24th century Romulan officer uniform',
        'Romulan Mid 24th Officer': 'Mid-24th century Romulan officer uniform',
        'Romulan Late 24th Officer': 'Late 24th century Romulan officer uniform',
        'Breen 24th': '24th century Breen refrigeration suit',
        'Breen 32nd': '32nd century Breen suit design',
        'IDW 2378': 'Non-canon IDW comics 2378 uniform design',
        'IDW 3069 A': 'Non-canon IDW "The Last Starship" 3069 design A',
        'IDW 3069 B': 'Non-canon IDW "The Last Starship" 3069 design B',
        'IDW 3069 C': 'Non-canon IDW "The Last Starship" 3069 design C',
        'Clear Skies 2410s': 'Non-canon fan design from "Clear Skies Perseverance"',
        'Volante Design 2411': 'Non-canon design by clothing brand Volante Design',
        'STO Odyssey': 'Star Trek Online Odyssey uniform (non-canon)',
        'STO Odyssey Commanding': 'Star Trek Online Odyssey command variant',
        'STO Odyssey Medical': 'Star Trek Online Odyssey medical variant',
        'STO Odyssey Enlisted': 'Star Trek Online Odyssey enlisted variant',
        'Sarell Expanse': 'Non-canon Sarell Expanse era uniform',
        'Sarell Expanse Alt': 'Non-canon Sarell Expanse alternate design',
        'Galaxy Quest Captain': 'Galaxy Quest commander uniform',
        'Galaxy Quest Crew': 'Galaxy Quest crew uniform',
        Orville: 'The Orville planetary union uniform',
        'Stargate SG-1': 'Stargate SG-1 military uniform',
        'Stargate Atlantis Early': 'Stargate Atlantis early expedition uniform',
        'Stargate Atlantis Late': 'Stargate Atlantis later uniform'
    },

    departments: {
        Command: 'Command division - Bridge officers, captains, and admirals',
        'Ops / Security / Engineering': 'Operations, Security, and Engineering divisions',
        'Ops / Security': 'Operations and Security divisions',
        'Ops / Engineering': 'Operations and Engineering divisions',
        'Ops / Engineering / Science': 'Operations, Engineering, and Science divisions',
        Science: 'Science division - Scientists and researchers',
        'Science / Medical': 'Science and Medical divisions',
        Medical: 'Medical division - Doctors and medical staff',
        Engineering: 'Engineering division - Technical specialists',
        Security: 'Security division - Tactical and security personnel',
        'Tal Shiar': 'Romulan Tal Shiar intelligence service',
        Intelligence: 'Starfleet Intelligence - Covert operations',
        Cadet: 'Starfleet Academy cadets',
        Enlisted: 'Enlisted personnel (non-commissioned)',
        'B&W / Undecided Cadet': 'uniform for undecided cadets or a grayscale look (Captain Proton)'
    },

    casual: {
        None: 'Unclothed',
        'Civilian Casual': 'Generic civilian casual wear',
        'Civilian Simple 1': 'Simple civilian outfit style 1',
        'Civilian Simple 2': 'Simple civilian outfit style 2',
        'Civilian Simple 3': 'Simple civilian outfit style 3',
        'Civilian Simple 4': 'Simple civilian outfit style 4',
        'Civilian Simple 5': 'Simple civilian outfit style 5',
        'Civilian Chef': 'Chef\'s uniform',
        'Bajoran Civilian': 'Typical Bajoran civilian clothing',
        'Civilian Klingon A': 'Klingon civilian attire style A',
        'Civilian Klingon B': 'Klingon civilian attire style B',
        'Civilian Klingon C': 'Klingon civilian attire style C',
        'Civilian Ferengi 24th': '24th century Ferengi civilian dress',
        'Civilian Federation A': 'Federation civilian clothing style A',
        'Civilian Federation B': 'Federation civilian clothing style B',
        'Civilian Federation C': 'Federation civilian clothing style C',
        'Civilian Federation D': 'Federation civilian clothing style D',
        'Civilian Federation E': 'Federation civilian clothing style E',
        'Civilian Federation F': 'Federation civilian clothing style F',
        'Civilian Federation G': 'Federation civilian clothing style G',
        'Civilian Federation H': 'Federation civilian clothing style H',
        'Civilian Federation I': 'Federation civilian clothing style I',
        'Civilian Federation J': 'Federation civilian clothing style J',
        'Leather Jacket Courrier': 'Leather jacket courier style',
        'Leather Jacket Spy': 'Leather jacket spy style',
        'Leather Light Jacket': 'Light leather jacket',
        'VinShari Coat': 'VinShari species traditional coat',
        'Orion Casual A': 'Orion casual clothing style A',
        'Orion Casual B': 'Orion casual clothing style B',
        'Orion Casual C': 'Orion casual clothing style C',
        'Eighteenth Century A': '18th century period costume style A',
        'Eighteenth Century B': '18th century period costume style B',
        'Eighteenth Century C': '18th century period costume style C',
        'Eighteenth Century D': '18th century period costume style D'
    }
}
